services:
  # OpenMRS:
  openmrs:
    image: mekomsolutions/openmrs:bahmni_latest
    build:
      context: ./openmrs
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      JAVA_OPTS: ${OPENMRS_JAVA_OPTS}
      MODULE_WEB_ADMIN: "true"
      DB_AUTO_UPDATE: "true"
      DB_CREATE_TABLES: "true"
      DB_HOST: mysql
      DB_DATABASE: openmrs
      DB_USERNAME: ${OPENMRS_DB_USER}
      DB_PASSWORD: ${OPENMRS_DB_PASSWORD}
      TZ: ${TIMEZONE}
    healthcheck:
      test: [ CMD, curl, "-f", "http://localhost:8080/openmrs/" ]
      timeout: 5s
    networks:
      bahmni:
        aliases:
          - openmrs
          - openmrs-tomcat
    ports:
      - "80:8080"
    volumes:
      - "openmrs-data:/usr/local/tomcat/.OpenMRS/"
      - "${OPENMRS_OWAS_PATH:-openmrs-owas}:/usr/local/tomcat/.OpenMRS/owa/"
      - "${OPENMRS_MODULES_PATH:-openmrs-modules}:/usr/local/tomcat/.OpenMRS/modules/"
      - "${OPENMRS_CONFIG_PATH:-openmrs-config}:/usr/local/tomcat/.OpenMRS/configuration/"
      - "${OPENMRS_CONFIG_CHECKSUMS_PATH:-openmrs-config-checksums}:/usr/local/tomcat/.OpenMRS/configuration_checksums/"
      - "${OPENMRS_LUCENE_PATH:-openmrs-lucene}:/usr/local/tomcat/.OpenMRS/lucene"
      - "${OPENMRS_ACTIVEMQ_PATH:-openmrs-active-mq}:/usr/local/tomcat/.OpenMRS/activemq-data"
      - "${BAHMNI_HOME_PATH:-bahmni-home}:/home/bahmni/"
      - "${BAHMNI_OBSCALCULATOR_PATH:-bahmni-obscalculator}:/usr/local/tomcat/.OpenMRS/obscalculator/"
      - ./properties/openmrs/:/etc/properties/
      - "${BAHMNI_IMAGE_PATH:-bahmni-images}:/home/bahmni/patient_images"

  # MySQL
  mysql:
    image: "mariadb:10.3"
    restart: unless-stopped
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --log-bin --binlog-format=ROW --server-id=2 --sync-binlog=1 --binlog-annotate-row-events=0"
    environment:
      MYSQL_DATABASE: openmrs
      MYSQL_USER: ${OPENMRS_DB_USER}
      MYSQL_PASSWORD: ${OPENMRS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: ${TIMEZONE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
    networks:
      bahmni:
        aliases:
          - openmrs-mysql
    ports:
      - "${MYSQL_PUBLIC_PORT:-3306}:3306"
    volumes:
      - "${MYSQL_DATADIR:-mysql-data}:/var/lib/mysql"
      - "${SQL_SCRIPTS_PATH:-./sqls}/mysql:/docker-entrypoint-initdb.d"

volumes:
  openmrs-data: ~
  mysql-data: ~
  openmrs-config: ~
  openmrs-config-checksums: ~
  openmrs-modules: ~
  openmrs-owas: ~
  bahmni-home: ~
  openmrs-active-mq: ~
  openmrs-lucene: ~
  bahmni-images: ~
  bahmni-obscalculator: ~

networks:
  bahmni:
